language: python
python:
    - "3.6.6"

# setup environment
#env:

#before_install:
  
#command to install
install:
#    - pip install -r requirements.txt
    - pip install -r requirements-build.txt

before_script:
#    - python manage.py migrate
    - python manage.py collectstatic
    - yes
#command to run tests
script:
    - python manage.py test
    
notifications:
    emails:
        recipients:
            - wunyanw@gmail.com
        on_success: never
        on_failure: always
